# Generated by Django 5.0.1 on 2024-02-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='static/uploads/')),
                ('service_title', models.CharField(max_length=200)),
                ('service_details', models.TextField()),
            ],
        ),
    ]
