# Generated by Django 5.0.1 on 2024-02-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_servicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('image1', models.ImageField(upload_to='static/uploads/')),
                ('image2', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
    ]
