# Generated by Django 5.0.1 on 2024-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_aboutusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_mobile', models.CharField(max_length=15)),
                ('admin_email', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
    ]
