# Generated by Django 5.0.1 on 2024-02-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_rename_why_choose_selector_whychoosemodel_why_choose_selector1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whychoosemodel',
            old_name='why_choose_selector1',
            new_name='why_choose_selector',
        ),
    ]
