# Generated by Django 5.0.1 on 2024-02-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_rename_why_choose_selector1_whychoosemodel_why_choose_selector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whychoosemodel',
            old_name='why_choose_selector',
            new_name='why_choose_selector1',
        ),
    ]
