# Generated by Django 5.0.1 on 2024-02-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_rename_why_choose_selector_whychoosemodel_why_choose_selector1'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychoosemodel',
            name='why_choose_selector2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whychoosemodel',
            name='why_choose_selector3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whychoosemodel',
            name='why_choose_selector4',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
