# Generated by Django 5.0.1 on 2024-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_whychoosemodel_why_choose_selector2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMambersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammambers_heading', models.CharField(max_length=200)),
                ('teammambers_image1', models.ImageField(upload_to='static/uploads/')),
                ('teammambers_image2', models.ImageField(upload_to='static/uploads/')),
                ('teammambers_image3', models.ImageField(upload_to='static/uploads/')),
                ('teammambers_image4', models.ImageField(upload_to='static/uploads/')),
                ('teammambers_name1', models.CharField(max_length=100)),
                ('teammambers_name2', models.CharField(max_length=100)),
                ('teammambers_name3', models.CharField(max_length=100)),
                ('teammambers_name4', models.CharField(max_length=100)),
                ('teammambers_details1', models.CharField(max_length=100)),
                ('teammambers_details2', models.CharField(max_length=100)),
                ('teammambers_details3', models.CharField(max_length=100)),
                ('teammambers_details4', models.CharField(max_length=100)),
            ],
        ),
    ]
