# Generated by Django 5.0.1 on 2024-02-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0011_newsfrommodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsFromModel',
        ),
    ]
