# Generated by Django 5.0.1 on 2024-02-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0012_delete_newsfrommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFromModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_from_heading', models.CharField(max_length=200)),
                ('news_from_image1', models.ImageField(upload_to='static/uploads/')),
                ('news_from_image2', models.ImageField(upload_to='static/uploads/')),
                ('news_from_date1', models.CharField(max_length=100)),
                ('news_from_date2', models.CharField(max_length=100)),
                ('news_from_details1', models.TextField()),
                ('news_from_details2', models.TextField()),
                ('news_from_steve1', models.CharField(max_length=100)),
                ('news_from_steve2', models.CharField(max_length=100)),
            ],
        ),
    ]
