# Generated by Django 5.0.1 on 2024-02-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_newsfrommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_from_heading1', models.CharField(max_length=200)),
                ('news_from_heading2', models.CharField(max_length=200)),
                ('news_from_image1', models.ImageField(upload_to='static/uploads/')),
                ('news_from_image2', models.ImageField(upload_to='static/uploads/')),
                ('news_from_name1', models.CharField(max_length=100)),
                ('news_from_name2', models.CharField(max_length=100)),
                ('news_from_founder1', models.TextField()),
                ('news_from_founder2', models.TextField()),
            ],
        ),
    ]
