# Generated by Django 5.0.1 on 2024-02-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0014_logisticsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logisticsmodel',
            old_name='news_from_founder1',
            new_name='logistics_founder1',
        ),
        migrations.RenameField(
            model_name='logisticsmodel',
            old_name='news_from_founder2',
            new_name='logistics_founder2',
        ),
        migrations.RenameField(
            model_name='logisticsmodel',
            old_name='news_from_heading1',
            new_name='logistics_heading1',
        ),
        migrations.RenameField(
            model_name='logisticsmodel',
            old_name='news_from_heading2',
            new_name='logistics_heading2',
        ),
        migrations.RenameField(
            model_name='logisticsmodel',
            old_name='news_from_image1',
            new_name='logistics_image1',
        ),
        migrations.RenameField(
            model_name='logisticsmodel',
            old_name='news_from_image2',
            new_name='logistics_image2',
        ),
        migrations.RenameField(
            model_name='logisticsmodel',
            old_name='news_from_name1',
            new_name='logistics_name1',
        ),
        migrations.RenameField(
            model_name='logisticsmodel',
            old_name='news_from_name2',
            new_name='logistics_name2',
        ),
    ]
