# Generated by Django 5.0.1 on 2024-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_feedback', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.ImageField(max_length=200, upload_to='')),
                ('contact_subject', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
